#!/usr/bin/env bash

#ddev-generated
## Description: Open a VSCode to a DDEV container
## Usage: code
## Example: "ddev code" Open VSCode remote to project's web container
## Example: "ddev code -d" Open VSCode remote to project's database container

## Requires DEV Containers extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

CODE_EXECUTABLE="code"

case ${1:-} in
-d | -db | --database)
    CODE_CONTAINER="ddev-${DDEV_PROJECT}-db"
    CODE_PATH=$HOME
    SERVICE="db"
    ;;
--) # End of all options.
    ;;
-?*)
    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
    ;;
*) # Default case
    CODE_CONTAINER="ddev-${DDEV_PROJECT}-web"
    CODE_PATH=/var/www/html
    SERVICE="web"
    ;;
esac

if [[ ${CODE_CONTAINER+x} ]]; then
    # Start DDEV, if not running.
    if [ "$DDEV_PROJECT_STATUS" != "running" ]; then
        ddev start
    fi
    
    # Remove DDEV's default .gitconfig file to allow DEV Containers extension to perform default behavior. https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
    if [ -e "$HOME"/.gitconfig ] && ddev exec --quiet --service "$SERVICE" command -v git > /dev/null 2>&1; then
        ddev exec --quiet --service "$SERVICE" rm -f "$HOME"/.gitconfig
    fi
    
    ${CODE_EXECUTABLE} --folder-uri "vscode-remote://attached-container+$(printf "%s" "$CODE_CONTAINER" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')${CODE_PATH}"

    # Wait for VSCode to finish copying .gitconfig and then re-add DDEV default configs.
    if [ -e "$HOME"/.gitconfig ] && ddev exec --quiet --service "$SERVICE" command -v git > /dev/null 2>&1; then
        COUNT=0
        MAX_COUNT=5
        until ddev exec --service "$SERVICE" "[ -e $HOME/.gitconfig ]" 2> /dev/null || [ $COUNT -gt $MAX_COUNT ]; do
            COUNT=$((COUNT+1))
            sleep 1
        done

        ddev exec --service "$SERVICE" git config --global core.autocrlf input
        ddev exec --service "$SERVICE" git config --global safe.directory "\*"
    fi
fi
